from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol


class AnalysisInsightsRepository(Protocol):
    def comparison_runs(self, load_case_id: str, baseline_run_id: str, target_run_id: str) -> list[dict[str, Any]]: ...

    def comparison_scalars(self, baseline_run_id: str, target_run_id: str) -> list[dict[str, Any]]: ...

    def comparison_series(self, baseline_run_id: str, target_run_id: str) -> list[dict[str, Any]]: ...

    def comparison_points(self, baseline_run_id: str, target_run_id: str, variable_key: str) -> list[dict[str, Any]]: ...

    def comparison_conditions(self, baseline_run_id: str, target_run_id: str) -> list[dict[str, Any]]: ...

    def trust_run(self, run_id: str) -> dict[str, Any] | None: ...

    def latest_run_id(self, load_case_id: str) -> str | None: ...

    def run_metadata(self, run_id: str) -> dict[str, Any] | None: ...

    def import_job(self, run_id: str) -> dict[str, Any] | None: ...

    def result_counts(self, run_id: str) -> dict[str, int]: ...

    def result_keys(self, run_id: str) -> set[str]: ...

    def active_catalog(self, load_case_id: str) -> dict[str, dict[str, Any]]: ...

    def result_unit_rows(self, run_id: str) -> list[tuple[Any, Any]]: ...

    def validations(self, run_id: str) -> list[dict[str, Any]]: ...


class AnalysisInsightsRepositoryProvider(Protocol):
    def __call__(self) -> AbstractContextManager[AnalysisInsightsRepository]: ...
