import { expect, test } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import path from 'node:path'
import { loginWorkspace } from './workspace-test-helpers'

test('항목 이름–값 위젯은 막대·점·선을 전환하고 저장한 설정을 복원한다', async ({ page }) => {
  test.setTimeout(150_000)
  const output = process.env.GUI_QA_OUTPUT_DIR
  if (output) mkdirSync(output, { recursive: true })
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.setViewportSize({ width: 1280, height: 800 })
  await loginWorkspace(page)
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.locator('.request-journey').getByRole('button', { name: /결과 검토|상세 분석/ }).click()
  await page.getByRole('button', { name: '분석 페이지 관리', exact: true }).click()
  const manager = page.getByRole('dialog', { name: '상세 분석 페이지 관리' })
  await manager.getByLabel('페이지 이름', { exact: true }).fill('항목 그래프 QA')
  await manager.getByRole('button', { name: '생성하고 위젯 배치' }).click()
  const assistant = page.locator('.assistant-drawer')
  await assistant.getByRole('button', { name: /항목 이름.*값 그래프/ }).click()
  await assistant.locator('.drawer-head button').click()
  const widget = page.locator('.widget-name_value').last()
  await widget.getByRole('button', { name: /설정/ }).click()
  const settings = page.locator('.widget-settings-drawer')
  const picker = settings.getByRole('region', { name: '데이터 항목', exact: true })
  const available = picker.getByRole('group', { name: '미적용 항목', exact: true })
  const applied = picker.getByRole('group', { name: '적용 항목', exact: true })
  await picker.getByRole('button', { name: '전체 제외', exact: true }).click()
  await expect(applied.getByRole('button')).toHaveCount(0)
  await expect(widget).toContainText('선택한 항목이 없습니다.')
  const firstLabel = await available.locator('strong').first().textContent()
  await picker.getByRole('textbox').fill(firstLabel!)
  await picker.getByRole('button', { name: '검색 결과 모두 추가', exact: true }).click()
  await picker.getByRole('textbox').fill('')
  await available.getByRole('button').first().click()
  await expect(applied.getByRole('button')).toHaveCount(2)
  await applied.getByRole('button').last().click()
  await expect(applied.getByRole('button')).toHaveCount(1)
  await available.getByRole('button').first().click()
  await expect(applied.getByRole('button')).toHaveCount(2)
  await settings.getByRole('combobox', { name: '시각화 유형', exact: true }).selectOption('result_table')
  await settings.getByRole('button', { name: '설정 완료' }).click()
  const table = page.locator('.widget-result_table').filter({ has: page.getByRole('heading', { name: /항목 이름.*값 그래프/ }) })
  await expect(table.locator('.table-row')).toHaveCount(2)
  await table.getByRole('button', { name: /설정/ }).click()
  await settings.getByRole('combobox', { name: '시각화 유형', exact: true }).selectOption('name_value')
  await settings.getByRole('combobox', { name: '시각화 유형', exact: true }).selectOption('kpi')
  await expect(settings.getByRole('status')).toContainText('한 항목만 선택')
  await settings.getByRole('combobox', { name: '시각화 유형', exact: true }).selectOption('name_value')
  await expect(applied.getByRole('button')).toHaveCount(1)
  await available.getByRole('button').first().click()
  await expect(applied.getByRole('button')).toHaveCount(2)
  await settings.getByLabel('제목', { exact: true }).fill('항목별 값 비교 QA')
  if (output) await page.screenshot({ path: path.join(output, 'item-picker-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(picker).toBeVisible()
  await expect.poll(() => picker.evaluate((element) => element.getBoundingClientRect().right <= innerWidth)).toBe(true)
  if (output) await page.screenshot({ path: path.join(output, 'item-picker-mobile.png') })
  await page.setViewportSize({ width: 1280, height: 800 })
  const style = settings.getByLabel('항목 그래프 표시 방식')
  await expect(style).toHaveValue('bar')
  await settings.getByRole('button', { name: '설정 완료' }).click()
  await expect(widget.locator('.recharts-bar-rectangle').first()).toBeVisible()
  await widget.getByRole('button', { name: /설정/ }).click()
  await style.selectOption('dot')
  await settings.getByRole('button', { name: '설정 완료' }).click()
  await expect(widget.locator('.recharts-line-dot').first()).toBeVisible()
  await expect(widget.locator('.recharts-bar-rectangle')).toHaveCount(0)
  await widget.getByRole('button', { name: /설정/ }).click()
  await style.selectOption('line')
  await settings.getByRole('button', { name: '설정 완료' }).click()
  await expect(widget.locator('.recharts-line-curve').first()).toBeVisible()
  await page.getByRole('button', { name: '레이아웃 저장', exact: true }).click()
  await expect(page.getByText(/레이아웃 v\d+ 저장 완료/)).toBeVisible()
  await page.getByRole('button', { name: '분석 페이지 관리', exact: true }).click()
  await manager.getByRole('button', { name: '게시', exact: true }).click()
  await manager.getByRole('button', { name: '닫기', exact: true }).click()
  await page.reload()
  await page.locator('.request-journey').getByRole('button', { name: /결과 검토|상세 분석/ }).click()
  await page.locator('.analysis-subtabs').getByRole('button', { name: /항목 그래프 QA/ }).click()
  await expect(widget.getByRole('heading', { name: '항목별 값 비교 QA' })).toBeVisible()
  await expect(widget.locator('.recharts-line-curve').first()).toBeVisible()
  await widget.getByRole('button', { name: /확대 보기/ }).click()
  await expect(widget).toHaveAttribute('aria-modal', 'true')
  await expect(page.locator('vite-error-overlay')).toHaveCount(0)
  expect(page.url()).toContain('/workspace/')
  expect(await page.title()).toBeTruthy()
  await expect(widget.locator('.recharts-line-dot')).toHaveCount(2)
  if (output) await page.screenshot({ path: path.join(output, 'name-value-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => widget.evaluate((element) => element.getBoundingClientRect().width <= innerWidth)).toBe(true)
  await expect(widget.locator('.recharts-line-dot').first()).toBeVisible()
  if (output) await page.screenshot({ path: path.join(output, 'name-value-mobile.png') })
  await page.keyboard.press('Escape')
  expect(errors).toEqual([])
})
