import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { loginWorkspace } from './workspace-test-helpers'

test('changing the result query hides previous data and ignores a delayed response', async ({ page }) => {
  await loginWorkspace(page, 'e2e-admin', '/workspace/catalog/schemas')
  await page.goto('/workspace/catalog/schemas')
  const screen = page.locator('.semantic-page')
  await screen.getByRole('button', { name: '3. 결과 조회', exact: true }).click()
  await screen.getByLabel('프로젝트', { exact: true }).selectOption('project-tv-001')
  await expect(screen.getByLabel('하중 경우', { exact: true })).not.toHaveValue('')
  const run = screen.getByLabel('Run ID (선택)', { exact: true })
  await run.fill('run-before')
  let finish: (() => void) | undefined
  let started: (() => void) | undefined
  const arrived = new Promise<void>((resolve) => { started = resolve })
  const release = new Promise<void>((resolve) => { finish = resolve })
  await page.route('**/api/semantic-mapping/results?**', async (route) => {
    started?.()
    await release
    await route.fulfill({ json: { widgets: [{ id: 'stale', title: '이전 대상 결과', type: 'kpi', status: 'READY', data: [{ value: 999 }] }] } })
  })
  const query = screen.getByRole('button', { name: '결과 조회', exact: true })
  await query.click()
  await arrived
  await run.fill('run-after')
  const completed = page.waitForResponse((response) => response.url().includes('/api/semantic-mapping/results?'))
  finish?.()
  await completed
  await expect(screen.getByText('이전 대상 결과', { exact: true })).toHaveCount(0)
  await run.fill('run-before')
  await expect(query).toBeEnabled()
  await query.click()
  await expect(screen.getByText('이전 대상 결과', { exact: true })).toBeVisible()
  await run.fill('run-next')
  await expect(screen.getByText('이전 대상 결과', { exact: true })).toHaveCount(0)
})

test('admin defines a sample recipe, publishes both definitions, imports and reopens the selected Run', async ({ page }) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await loginWorkspace(page, 'e2e-admin', '/workspace/catalog/schemas')
  await page.goto('/workspace/catalog/schemas')
  const screen = page.locator('.semantic-page')
  await expect(screen.getByRole('heading', { name: '결과 의미 연결' })).toBeVisible()
  const suffix = Date.now().toString()
  const recipeName = `QA 레시피 ${suffix}`
  const templateName = `QA 템플릿 ${suffix}`
  const sample = { name: 'sample.csv', mimeType: 'text/csv', buffer: Buffer.from('stress\n120\n') }
  const inspected = page.waitForResponse((response) => response.url().endsWith('/api/semantic-mapping/inspect') && response.request().method() === 'POST')
  await screen.locator('.file-drop input').setInputFiles(sample)
  expect((await inspected).status()).toBe(200)
  await expect(screen.getByLabel('결과 항목', { exact: true })).toHaveValue('')
  await screen.getByTitle('새 결과 항목', { exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '결과 항목 정의' })
  await dialog.getByLabel('표시명', { exact: true }).fill('QA 최대 응력')
  await dialog.getByLabel('고정 항목 키').fill(`qa_stress_${suffix}`)
  await dialog.getByLabel('기준 단위', { exact: true }).fill('MPa')
  await dialog.getByRole('button', { name: '결과 항목 저장', exact: true }).click()
  await expect(dialog).toBeHidden()
  await screen.getByLabel('원본 단위', { exact: true }).fill('MPa')
  await screen.getByRole('button', { name: '위젯 추가', exact: true }).click()
  await screen.getByLabel('위젯 제목').fill('QA 응력 카드')
  await screen.getByLabel('레시피 이름', { exact: true }).fill(recipeName)
  await screen.getByLabel('템플릿 이름', { exact: true }).fill(templateName)
  await screen.getByRole('button', { name: '미리보기 실행', exact: true }).click()
  await expect(screen.locator('.semantic-result-kpi strong')).toHaveText('120.00')
  await screen.getByRole('button', { name: '레시피 저장', exact: true }).click()
  await expect(screen.getByRole('status')).toContainText('저장했습니다')
  await screen.getByRole('button', { name: '템플릿 저장', exact: true }).click()
  await expect(screen.getByRole('status')).toContainText(templateName)
  const activated = page.waitForResponse((response) => response.url().endsWith('/api/semantic-mapping/activate-bundle'))
  await screen.getByRole('button', { name: /함께 활성화/ }).click()
  expect((await activated).status()).toBe(200)
  await screen.getByRole('button', { name: '2. 폴더 연결', exact: true }).click()
  await screen.getByLabel('프로젝트', { exact: true }).selectOption('project-tv-001')
  await screen.getByLabel('의뢰', { exact: true }).selectOption('request-drop-001')
  await screen.getByLabel('하중 경우', { exact: true }).selectOption('loadcase-drop-bottom-001')
  await screen.getByRole('checkbox', { name: new RegExp(recipeName) }).check()
  await screen.getByLabel('표시 템플릿', { exact: true }).selectOption({ label: `${templateName} · 활성 v1` })
  await screen.getByLabel('등록할 결과 파일').setInputFiles(sample)
  const imported = page.waitForResponse((response) => response.url().endsWith('/api/semantic-mapping/import'))
  await screen.getByRole('button', { name: '단일 파일 가져오기', exact: true }).click()
  const importedResponse = await imported
  expect(importedResponse.status()).toBe(200)
  const { run_id: runId } = await importedResponse.json()
  expect(runId).toBeTruthy()
  await page.goto(`/workspace/requests?project=project-tv-001&request=request-drop-001&loadCase=loadcase-drop-bottom-001&run=${runId}&view=compare`)
  const runPanel = page.getByRole('region', { name: '레시피로 연결한 결과' })
  await expect(runPanel.getByText('QA 응력 카드')).toBeVisible()
  await expect(runPanel.locator('.semantic-result-kpi strong')).toHaveText('120.00')
  await page.goto('/workspace/catalog/schemas')
  await screen.getByLabel('저장된 레시피').selectOption({ label: `${recipeName} · v1` })
  await screen.locator('.file-drop input').setInputFiles(sample)
  await expect(screen.getByLabel('결과 항목', { exact: true })).not.toHaveValue('')
  expect(errors).toEqual([])
})

test('viewer cannot edit semantic configuration or publish a recipe', async ({ page }) => {
  await loginWorkspace(page, 'e2e-viewer')
  const catalog = await page.request.get('/api/semantic-mapping/catalog')
  expect(catalog.status()).toBe(403)
  const create = await page.request.post('/api/semantic-mapping/items', { data: { definition: { key: 'denied', label: 'Denied' } } })
  expect(create.status()).toBe(403)
  const publish = await page.request.post('/api/semantic-mapping/activate-bundle', { data: { recipe_id: 'denied', recipe_version: 1, template_id: 'denied', template_version: 1 } })
  expect(publish.status()).toBe(403)
})

test('the documented sample renders numeric bars, curve, scatter, table and gauge', async ({ page }) => {
  await loginWorkspace(page, 'e2e-admin', '/workspace/catalog/schemas')
  const definitions = JSON.parse(readFileSync('../examples/semantic-mapping/definitions.json', 'utf8'))
  const imported = await page.request.post('/api/semantic-mapping/import-definitions', { data: definitions })
  expect(imported.status()).toBe(201)
  await page.goto('/workspace/catalog/schemas')
  const screen = page.locator('.semantic-page')
  await screen.getByLabel('저장된 레시피').selectOption({ label: '예제 CSV 읽기 · v1' })
  await screen.getByLabel('저장된 템플릿').selectOption({ label: '예제 결과 위젯 6종 · v1' })
  await screen.locator('.file-drop input').setInputFiles('../examples/semantic-mapping/result.csv')
  await screen.getByRole('button', { name: '미리보기 실행', exact: true }).click()
  const preview = screen.locator('.preview-card')
  await expect(preview.locator('.semantic-result-widget')).toHaveCount(6)
  await expect(preview.locator('.semantic-result-widget.invalid')).toHaveCount(0)
  await expect(preview.locator('.recharts-bar-rectangle path')).toHaveCount(1)
  await expect(preview.locator('.recharts-line-curve')).toBeVisible()
  await expect(preview.locator('.recharts-scatter-symbol')).toHaveCount(1)
  await expect(preview.getByRole('cell', { name: '120', exact: true })).toBeVisible()
  await expect(preview.getByRole('cell', { name: '2', exact: true })).toBeVisible()
  await expect(preview.getByText('PASS', { exact: true })).toBeVisible()
  if (process.env.SEMANTIC_QA_SCREENSHOT) await preview.screenshot({ path: process.env.SEMANTIC_QA_SCREENSHOT })
})
