import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { loginWorkspace } from './workspace-test-helpers'

for (const extension of ['csv', 'json']) {
  test(`issue ${extension} sample: item editing, widgets, atomic save, reopen and Run`, async ({ page }, testInfo) => {
    test.setTimeout(240_000)
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('console', (message) => { if (message.type() === 'error' && !message.text().includes('401')) errors.push(message.text()) })
    await loginWorkspace(page, 'e2e-admin', '/workspace/catalog/schemas')
    await page.goto('/workspace/catalog/schemas')
    await expect(page).toHaveTitle(/.+/)
    const screen = page.locator('.semantic-page')
    await expect(screen.getByRole('heading', { name: '결과 의미 연결' })).toBeVisible()
    const inspector = screen.getByTestId('semantic-sample-inspector')
    const filename = extension === 'csv' ? 'issue_23.csv' : 'issue_24.json'
    const sample = { name: filename, mimeType: extension === 'csv' ? 'text/csv' : 'application/json', buffer: readFileSync(`../backend/tests/fixtures/semantic_samples/${filename}`) }
    await inspector.locator('input[type=file]').setInputFiles(sample)
    await expect(inspector).toContainText('-311.643')
    await expect(screen.getByLabel('원본 필드', { exact: true })).toHaveCount(0)
    await expect(inspector.getByRole('button', { name: /선택 값을 결과 항목으로 연결/ })).toContainText('(43)')
    await inspector.getByRole('button', { name: /선택 값을 결과 항목으로 연결/ }).click()
    const mappings = screen.getByLabel('원본 필드', { exact: true })
    await expect(mappings).toHaveCount(43, { timeout: 90_000 })
        const topRow = screen.locator('.mapping-row').filter({ has: page.locator('input[aria-label="원본 필드"][value="#/Set Top Disp. (mm)"]') })
    const firstId = await topRow.getByLabel('결과 항목', { exact: true }).inputValue()
    expect(firstId).toBeTruthy()
    await screen.getByRole('button', { name: '매핑 복제', exact: true }).first().click()
    await expect(mappings).toHaveCount(44)
    await screen.getByRole('button', { name: '매핑 삭제', exact: true }).first().click()
    await expect(mappings).toHaveCount(43)
    await screen.getByRole('button', { name: '삭제 되돌리기', exact: true }).click()
    await expect(mappings).toHaveCount(44)
    await screen.getByRole('button', { name: '매핑 삭제', exact: true }).first().click()
    await expect(mappings).toHaveCount(43)

    await topRow.getByTitle('결과 항목 수정', { exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '결과 항목 정의' })
    await dialog.getByLabel('표시명', { exact: true }).fill('상단 변위')
    await dialog.getByRole('button', { name: '결과 항목 저장', exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(topRow.getByLabel('결과 항목', { exact: true })).toHaveValue(firstId)
    await screen.getByRole('button', { name: '전체 항목 요약표 추가', exact: true }).click()
    await screen.getByRole('button', { name: '위젯 추가', exact: true }).click()
    const editors = screen.locator('.semantic-widget-editor')
    await expect(editors).toHaveCount(2)
    await editors.last().getByLabel('위젯 결과 항목').selectOption(firstId)
    await expect(editors.last().getByLabel('위젯 제목')).toHaveValue('상단 변위')
    await expect(editors.last().getByLabel('위젯 종류').locator('option[value=line]')).toHaveAttribute('disabled', '')
    await editors.first().getByLabel('표시 자릿수').fill('3')
    await editors.last().getByLabel('표시 자릿수').fill('3')
    const preview = screen.locator('.preview-panel')
    await expect(preview.locator('.semantic-result-widget.ready')).toHaveCount(2)
    await expect(preview.locator('.semantic-result-kpi strong')).toHaveText('-311.643')
    await expect(preview.locator('.semantic-result-table tbody tr')).toHaveCount(43)
    const coordinate = preview.locator('.semantic-result-table tbody tr').filter({ hasText: 'Set CG Coord. · Z' })
    await expect(coordinate).toContainText('-159.909')
    await expect(coordinate).toContainText('mm')
    await expect(preview).toContainText(/0\s*curve/)
    const suffix = `${extension}-${Date.now()}`
    const recipeName = `Issue ${suffix}`
    const templateName = `Issue widgets ${suffix}`
    await screen.getByLabel('레시피 이름', { exact: true }).fill(recipeName)
    await screen.getByLabel('템플릿 이름', { exact: true }).fill(templateName)
    const saving = page.waitForResponse((response) => response.url().endsWith('/semantic-mapping/configurations') && response.request().method() === 'POST')
    await screen.getByRole('button', { name: '결과 설정 저장', exact: true }).click()
    const response = await saving
    expect(response.status(), await response.text()).toBe(201)
    const saved = await response.json()
    expect(saved.recipe.definition.mappings).toHaveLength(43)
    expect(saved.template.definition.widgets).toHaveLength(2)
    expect(saved.recipe.definition.display_template_id).toBe(saved.template.id)
    await expect(preview.locator('.semantic-result-widget.ready')).toHaveCount(2)
    const impact = page.waitForResponse((response) => response.url().endsWith('/semantic-mapping/impact-bundle'))
    await screen.getByRole('button', { name: /활성화 영향 미리보기/ }).click()
    expect((await impact).status()).toBe(200)
    const activated = page.waitForResponse((response) => response.url().endsWith('/semantic-mapping/activate-bundle'))
    await page.getByRole('dialog', { name: '활성화 영향 미리보기' }).getByRole('button', { name: '검토 후 활성화', exact: true }).click()
    expect((await activated).status()).toBe(200)
    await screen.getByRole('button', { name: '2. 폴더 연결', exact: true }).click()
    await screen.getByLabel('프로젝트', { exact: true }).selectOption('project-tv-001')
    await screen.getByLabel('의뢰', { exact: true }).selectOption('request-drop-001')
    await screen.getByLabel('하중 경우', { exact: true }).selectOption('loadcase-drop-bottom-001')
    await screen.getByRole('checkbox', { name: new RegExp(recipeName) }).check()
    await screen.getByLabel('표시 템플릿', { exact: true }).selectOption(saved.template.id)
    await screen.getByLabel('등록할 결과 파일').setInputFiles(sample)
    const importing = page.waitForResponse((response) => response.url().endsWith('/semantic-mapping/import'))
    await screen.getByRole('button', { name: '단일 파일 가져오기', exact: true }).click()
    const imported = await importing
    expect(imported.status(), await imported.text()).toBe(200)
    const { run_id: runId } = await imported.json()
    await page.goto(`/workspace/requests?project=project-tv-001&request=request-drop-001&loadCase=loadcase-drop-bottom-001&run=${runId}&view=compare`)
    const panel = page.getByRole('region', { name: '레시피로 연결한 결과' })
    await expect(panel.locator('.semantic-result-kpi strong')).toHaveText('-311.643')
    await expect(panel.locator('.semantic-result-table tbody tr')).toHaveCount(43)
    await page.goto('/workspace/catalog/schemas')
    const opening = page.waitForResponse((response) => response.url().endsWith(`/semantic-mapping/configurations/${saved.recipe.id}`))
    await screen.getByLabel('저장된 레시피', { exact: true }).selectOption(saved.recipe.id)
    expect((await opening).status()).toBe(200)
    await expect(editors).toHaveCount(2)
    await expect(screen.getByLabel('템플릿 이름', { exact: true })).toHaveValue(templateName)
    await inspector.locator('input[type=file]').setInputFiles(sample)
    await expect(preview.locator('.semantic-result-kpi strong')).toHaveText('-311.643')
    await preview.locator('.semantic-result-grid').evaluate((element) => element.scrollIntoView({ block: 'center' }))
    for (const editor of await editors.all()) {
      const bounds = await editor.boundingBox()
      expect(bounds).not.toBeNull()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width + 1)
    }
    await page.screenshot({ path: testInfo.outputPath(`issue-${extension}-widgets.png`) })
    await page.setViewportSize({ width: 390, height: 844 })
    await editors.last().scrollIntoViewIfNeeded()
    await expect(editors.last().getByLabel('위젯 제목')).toBeVisible()
    for (const editor of await editors.all()) {
      const bounds = await editor.boundingBox()
      expect(bounds).not.toBeNull()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(391)
      for (const control of await editor.locator('input,select,button').all()) {
        const controlBounds = await control.boundingBox()
        if (!controlBounds) continue
        expect(controlBounds.x).toBeGreaterThanOrEqual(bounds!.x)
        expect(controlBounds.x + controlBounds.width).toBeLessThanOrEqual(bounds!.x + bounds!.width + 1)
      }
    }
    await page.screenshot({ path: testInfo.outputPath(`issue-${extension}-mobile.png`) })
    await expect(page.locator('vite-error-overlay')).toHaveCount(0)
    expect(errors).toEqual([])
  })
}
