import { lazy, Suspense } from 'react'
import { AlertTriangle, Download, LoaderCircle, Settings2, X } from 'lucide-react'
import type { ReportExportController } from './useReportExportController'

const ReportLayoutEditor = lazy(() => import('./ReportLayoutEditor').then(({ ReportLayoutEditor: Editor }) => ({ default: Editor })))
const reportEditorFallback = <div className="full-state"><LoaderCircle className="spin" /> 화면을 준비하고 있습니다.</div>

export function ReportExportDialog({ controller }: { controller: ReportExportController }) {
  const { close, cancel, downloadReport, isLayoutEditing, isOpen, removeReportLayout, removeReportTemplate, reportContents, reportDraft, reportError, reportExporting, reportLayoutDraft, reportLayoutVersions, reportLayouts, reportOverview, reportPageId, reportRunId, reportRuns, reportSource, reportTemplates, saveReportLayout, selectComparisonReportRun, selectReportLayout, selectReportLayoutVersion, selectReportPage, selectReportRun, setIsLayoutEditing, setReportLayoutDraft, updateDraft, uploadReportTemplate } = controller
  if (!isOpen || !reportDraft || !reportOverview || !reportLayoutDraft || !reportSource) return null
  const pageOptions = controller.reportPageOptions
  const isSystem = Boolean(reportLayouts.find((item) => item.id === reportLayoutDraft.id)?.is_system)
  return <div className="drawer-backdrop report-backdrop" onMouseDown={() => { if (!reportExporting) close() }}>
    <section className="report-export-dialog" role="dialog" aria-modal="true" aria-labelledby="report-export-title" onMouseDown={(event) => event.stopPropagation()}>
      <header><div><span>POWERPOINT EXPORT</span><h2 id="report-export-title">{reportOverview.load_case.request_title} 보고서</h2><p>선택한 평가 데이터와 아래 문구로 편집 가능한 PPTX를 생성합니다.</p></div><button aria-label="닫기" onClick={close} disabled={reportExporting}><X /></button></header>
      <div className="report-layout-toolbar">
        {reportSource.kind === 'run_compare_review' ? <><label><span>기준 Run</span><select aria-label="보고서 기준 Run 선택" value={reportSource.baselineRunId} onChange={(event) => void selectComparisonReportRun('baseline', event.target.value)}>{reportRuns.filter((run) => run.id !== reportSource.targetRunId).map((run) => <option key={run.id} value={run.id}>{`Run ${run.run_no} · ${run.overall_verdict}`}</option>)}</select></label><label><span>대상 Run</span><select aria-label="보고서 대상 Run 선택" value={reportSource.targetRunId} onChange={(event) => void selectComparisonReportRun('target', event.target.value)}>{reportRuns.filter((run) => run.id !== reportSource.baselineRunId).map((run) => <option key={run.id} value={run.id}>{`Run ${run.run_no} · ${run.overall_verdict}`}</option>)}</select></label></> : <><label><span>분석 페이지</span><select aria-label="보고서 분석 페이지" value={reportPageId} onChange={(event) => void selectReportPage(event.target.value)}>{pageOptions.map((page) => <option key={page.id} value={page.id}>{page.name}</option>)}</select></label><label><span>Run</span><select aria-label="보고서 Run 선택" value={reportRunId} onChange={(event) => void selectReportRun(event.target.value)}>{reportRuns.map((run) => <option key={run.id} value={run.id}>{`Run ${run.run_no} · ${run.overall_verdict} · ${run.completed_at ? new Date(run.completed_at).toLocaleString('ko-KR') : run.status}`}</option>)}</select></label></>}
        <label><span>출력 레이아웃</span><select value={reportLayoutDraft.id} onChange={(event) => void selectReportLayout(event.target.value)}>{reportLayouts.map((item) => <option key={item.id} value={item.id}>{item.name} · v{item.version}</option>)}</select></label>
        <label className="report-version-select"><span>출력 버전</span><select value={reportLayoutDraft.version} onChange={(event) => void selectReportLayoutVersion(Number(event.target.value))}>{reportLayoutVersions.map((item) => <option key={item.version} value={item.version}>v{item.version} · {new Date(item.created_at).toLocaleDateString('ko-KR')}</option>)}</select></label>
        <button onClick={() => setIsLayoutEditing((current) => !current)}><Settings2 /> {isLayoutEditing ? '편집 닫기' : '레이아웃 편집·관리'}</button>
      </div>
      {isLayoutEditing && <div data-testid="ppt-layout-editor"><Suspense fallback={reportEditorFallback}><ReportLayoutEditor layout={reportLayoutDraft} overview={reportOverview} contents={reportContents} templates={reportTemplates} isSystem={isSystem} onChange={setReportLayoutDraft} onTemplateUpload={(file) => void uploadReportTemplate(file)} onTemplateDelete={(id) => void removeReportTemplate(id)} onSave={() => void saveReportLayout(false)} onSaveAs={() => void saveReportLayout(true)} onDelete={() => void removeReportLayout()} /></Suspense></div>}
      <div className="report-export-grid">
        <label><span>작성자 *</span><input value={reportDraft.author} onChange={(event) => updateDraft('author', event.target.value)} placeholder="홍길동" /></label><label><span>개발단계 *</span><input value={reportDraft.developmentStage} onChange={(event) => updateDraft('developmentStage', event.target.value)} placeholder="DV 1차" /></label><label><span>작성날짜 *</span><input value={reportDraft.reportDate} onChange={(event) => updateDraft('reportDate', event.target.value)} placeholder="2026.07.23." /></label><label><span>시뮬레이션 종류 *</span><input value={reportDraft.reliabilityName} onChange={(event) => updateDraft('reliabilityName', event.target.value)} placeholder="낙하 / Side Clamp / 적재" /></label>
        <label className="wide"><span>검토 목적 *</span><input value={reportDraft.reviewPurpose} onChange={(event) => updateDraft('reviewPurpose', event.target.value)} placeholder="오픈셀 응력 평가" /></label><label><span>검토 사양 조건 *</span><textarea value={reportDraft.reviewConditions} onChange={(event) => updateDraft('reviewConditions', event.target.value)} /></label><label><span>검토 결과 *</span><textarea value={reportDraft.reviewResult} onChange={(event) => updateDraft('reviewResult', event.target.value)} /></label><label className="wide"><span>검토 결론 *</span><textarea value={reportDraft.reviewConclusion} onChange={(event) => updateDraft('reviewConclusion', event.target.value)} /></label>
      </div>
      <aside><strong>자동 포함 자료</strong><span>시간 이력 그래프 {new Set(reportOverview.time_series.map((item) => item.variable_key)).size}개 · 정량 결과 {reportOverview.scalar_results.length}개 · 이미지/미디어 {reportOverview.media.length}개</span><small>선택한 평가에 연결된 데이터만 포함합니다. 영상·애니메이션은 호환성을 위해 자산 정보 페이지로 생성됩니다.</small></aside>
      {reportError && <div className="report-export-error"><AlertTriangle /> {reportError}</div>}
      <footer><button onClick={cancel} disabled={reportExporting}>취소</button><button className="primary" onClick={() => void downloadReport()} disabled={reportExporting || !reportDraft.author.trim() || (reportSource.kind === 'analysis_page' && !reportRunId) || (reportLayoutDraft.templateSource === 'pptx_upload' && !reportLayoutDraft.templateAssetId)}>{reportExporting ? <LoaderCircle className="spin" /> : <Download />} PPTX 생성</button></footer>
    </section>
  </div>
}
